---
name: Test app_frontend

on:
  push:
    branches: ["main"]
    paths:
      - "app_frontend/**"

  pull_request:
    branches: ["main"]
    paths:
      - "app_frontend/**"

  workflow_dispatch:

jobs:
  tests:
    name: "React: app_frontend node: ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_frontend

    strategy:
      matrix:
        node-version: ["20", "22", "24"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: app_frontend

      - name: Run Vitest
        run: npm run test
        working-directory: app_frontend

      - name: Run Lint
        run: npm run lint
        working-directory: app_frontend
